class DomainException(Exception): ...


class FieldNotFoundError(DomainException): ...


class InvalidCropNameError(DomainException): ...


class InvalidOwnerNameError(DomainException): ...


class InvalidGeometryError(DomainException): ...


class AreaValidationError(DomainException): ...
